name: xcalc-tests
channels:
    - conda-forge
    - nodefaults
dependencies:
    - dask
    - xarray
    - xclim
    - netCDF4
    - pytest
    - pytest-cov
    - pytest-env

    - pip:
      - pyhomogenize>=0.3.0
